---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: aravindroy1/washify-review:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: washify-config
            - secretRef:
                name: washify-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
