---
apiVersion: v1
kind: Service
metadata:
  namespace: washify-dev-ns
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

