apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: washify-dev-ns
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    protocol: {{ .Values.gateway.protocol }}
    port: {{ .Values.gateway.port }}
