apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: default
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/auth
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: auth-service
      port: 8000

  - matches:
    - path:
        type: PathPrefix
        value: /api/car-wash
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: car-wash-service
      port: 8000

  - matches:
    - path:
        type: PathPrefix
        value: /api/booking
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: booking-service
      port: 8000

  - matches:
    - path:
        type: PathPrefix
        value: /api/review
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: review-service
      port: 8000

  - matches:
    - path:
        type: PathPrefix
        value: /api/notification
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: notification-service
      port: 8000

  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend-service
      port: 80
