---
apiVersion: v1
kind: Service
metadata:
  name: car-wash-service
spec:
  type: NodePort
  selector:
    app: car-wash-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
