---
apiVersion: v1
kind: Service
metadata:
  namespace: washify-dev-ns
  name: car-wash-service
spec:
  type: ClusterIP
  selector:
    app: car-wash-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

