apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-auth-service
  namespace: argocd
  labels:
    environment: dev
    project: washify
    service: auth-service
spec:
  project: default
  source:
    repoURL: https://github.com/WashifyApp/washify-gitops.git
    targetRevision: main
    path: dev/apps/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: washify-dev-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
