# ArgoCD App-of-Apps — DEV Cluster Root
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: washify-dev-app-of-apps
  namespace: argocd
  labels:
    environment: dev
    project: washify
spec:
  project: default
  source:
    repoURL: https://github.com/WashifyApp/washify-gitops.git
    targetRevision: main
    path: dev/apps
  destination:
    server: https://kubernetes.default.svc   # <-- your DEV cluster API server
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
